# Generated by Django 2.1.1 on 2018-11-20 21:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_auto_20181120_2117'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='primage',
            options={'verbose_name': 'Фото продукта', 'verbose_name_plural': 'Фото продукта'},
        ),
        migrations.RemoveField(
            model_name='product',
            name='image',
        ),
    ]
